clone_folder: c:\projects\go\src\github.com\tus\tusd

environment:
  GOPATH: c:\projects\go
  GO111MODULE: on

build_script:
  - set PATH=%GOPATH%\bin;%PATH%
  - go env
  - go version

test_script:
  - go test ./pkg/...
  - go vet ./pkg/...
